import Foundation
import McClawKit

/// A single message in a chat session.
struct ChatMessage: Identifiable, Codable, Sendable {
    let id: UUID
    let role: MessageRole
    var content: String
    let timestamp: Date
    let sessionId: String
    var attachments: [Attachment]
    var toolCalls: [ToolCall]
    var generatedImages: [GeneratedImage]
    var isStreaming: Bool
    /// Whether the assistant is currently generating an image (shows shimmer placeholder).
    var isGeneratingImage: Bool
    /// Which CLI provider handled this message (e.g. "claude", "gemini").
    var providerId: String?
    /// If non-nil, this message displays an install progress view for the given plan.
    var installPlanId: UUID?
    /// Interactive prompts detected in the AI response for user input.
    var interactivePrompts: [InteractivePromptKit.InteractivePrompt]
    /// User responses to interactive prompts.
    var promptResponses: [InteractivePromptKit.PromptResponse]
    /// Path to the plan file generated in Plan Mode (e.g. ~/.claude/plans/xxx.md).
    var planFilePath: String?
    /// Git/platform actions proposed by the AI that require user confirmation.
    var gitActions: [PendingGitAction]

    init(
        id: UUID = UUID(),
        role: MessageRole,
        content: String,
        timestamp: Date = Date(),
        sessionId: String,
        attachments: [Attachment] = [],
        toolCalls: [ToolCall] = [],
        generatedImages: [GeneratedImage] = [],
        isStreaming: Bool = false,
        isGeneratingImage: Bool = false,
        providerId: String? = nil,
        installPlanId: UUID? = nil,
        interactivePrompts: [InteractivePromptKit.InteractivePrompt] = [],
        promptResponses: [InteractivePromptKit.PromptResponse] = [],
        planFilePath: String? = nil,
        gitActions: [PendingGitAction] = []
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.sessionId = sessionId
        self.attachments = attachments
        self.toolCalls = toolCalls
        self.generatedImages = generatedImages
        self.isStreaming = isStreaming
        self.isGeneratingImage = isGeneratingImage
        self.providerId = providerId
        self.installPlanId = installPlanId
        self.interactivePrompts = interactivePrompts
        self.promptResponses = promptResponses
        self.planFilePath = planFilePath
        self.gitActions = gitActions
    }

    // Custom Codable to maintain backwards compatibility with existing session files
    enum CodingKeys: String, CodingKey {
        case id, role, content, timestamp, sessionId, attachments, toolCalls
        case generatedImages, isStreaming, isGeneratingImage, providerId, installPlanId
        case interactivePrompts, promptResponses, planFilePath, gitActions
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        role = try container.decode(MessageRole.self, forKey: .role)
        content = try container.decode(String.self, forKey: .content)
        timestamp = try container.decode(Date.self, forKey: .timestamp)
        sessionId = try container.decode(String.self, forKey: .sessionId)
        attachments = try container.decodeIfPresent([Attachment].self, forKey: .attachments) ?? []
        toolCalls = try container.decodeIfPresent([ToolCall].self, forKey: .toolCalls) ?? []
        generatedImages = try container.decodeIfPresent([GeneratedImage].self, forKey: .generatedImages) ?? []
        isStreaming = try container.decodeIfPresent(Bool.self, forKey: .isStreaming) ?? false
        isGeneratingImage = try container.decodeIfPresent(Bool.self, forKey: .isGeneratingImage) ?? false
        providerId = try container.decodeIfPresent(String.self, forKey: .providerId)
        installPlanId = try container.decodeIfPresent(UUID.self, forKey: .installPlanId)
        interactivePrompts = try container.decodeIfPresent([InteractivePromptKit.InteractivePrompt].self, forKey: .interactivePrompts) ?? []
        promptResponses = try container.decodeIfPresent([InteractivePromptKit.PromptResponse].self, forKey: .promptResponses) ?? []
        planFilePath = try container.decodeIfPresent(String.self, forKey: .planFilePath)
        gitActions = try container.decodeIfPresent([PendingGitAction].self, forKey: .gitActions) ?? []
    }
}

/// An image generated by an AI provider.
struct GeneratedImage: Identifiable, Codable, Sendable {
    let id: UUID
    let filePath: String
    let prompt: String
    let providerUsed: String
    let timestamp: Date

    init(
        id: UUID = UUID(),
        filePath: String,
        prompt: String,
        providerUsed: String,
        timestamp: Date = Date()
    ) {
        self.id = id
        self.filePath = filePath
        self.prompt = prompt
        self.providerUsed = providerUsed
        self.timestamp = timestamp
    }
}

/// A generated image indexed with its source session for the Multimedia gallery.
struct IndexedImage: Identifiable, Codable, Sendable {
    let imageId: UUID
    let sessionId: String
    let sessionTitle: String
    let filePath: String
    let prompt: String
    let providerUsed: String
    let timestamp: Date

    var id: UUID { imageId }
}

/// Who sent the message.
enum MessageRole: String, Codable, Sendable {
    case user
    case assistant
    case system
    case tool
}

/// File attachment on a message.
struct Attachment: Identifiable, Codable, Sendable {
    let id: UUID
    let filename: String
    let mimeType: String
    let filePath: String
    let fileSize: Int64

    init(
        id: UUID = UUID(),
        filename: String,
        mimeType: String,
        filePath: String,
        fileSize: Int64
    ) {
        self.id = id
        self.filename = filename
        self.mimeType = mimeType
        self.filePath = filePath
        self.fileSize = fileSize
    }
}

/// A tool call made by the assistant.
struct ToolCall: Identifiable, Codable, Sendable {
    let id: String
    let name: String
    let arguments: String
    var result: String?
    var status: ToolCallStatus

    init(
        id: String,
        name: String,
        arguments: String,
        result: String? = nil,
        status: ToolCallStatus = .pending
    ) {
        self.id = id
        self.name = name
        self.arguments = arguments
        self.result = result
        self.status = status
    }
}

enum ToolCallStatus: String, Codable, Sendable {
    case pending
    case running
    case completed
    case failed
}

/// Information about a chat session.
struct SessionInfo: Identifiable, Codable, Sendable {
    let id: String
    let title: String
    let createdAt: Date
    var lastMessageAt: Date
    let sessionType: SessionType
    var messageCount: Int
    var cliProvider: String?
    /// If non-nil, the session belongs to this project and won't show in the main sidebar.
    var projectId: String?
    /// If non-nil, the session is a Git conversation associated with this repo (e.g. "owner/repo").
    var gitRepoFullName: String?
}

// MARK: - Projects

/// A project that groups chat sessions together.
struct ProjectInfo: Identifiable, Codable, Sendable {
    let id: String
    var name: String
    var description: String
    /// Rules/instructions that the AI must follow when chatting within this project.
    var rules: String
    /// Path to a cover image for the project (relative to ~/.mcclaw/projects/).
    var imagePath: String?
    /// Filesystem directories associated with this project.
    var directories: [String]
    let createdAt: Date
    var updatedAt: Date
    var sessionIds: [String]

    init(
        id: String = UUID().uuidString,
        name: String,
        description: String = "",
        rules: String = "",
        imagePath: String? = nil,
        directories: [String] = [],
        createdAt: Date = Date(),
        updatedAt: Date = Date(),
        sessionIds: [String] = []
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.rules = rules
        self.imagePath = imagePath
        self.directories = directories
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.sessionIds = sessionIds
    }

    // Custom Codable to handle backward compatibility (missing 'directories' key in old files)
    enum CodingKeys: String, CodingKey {
        case id, name, description, rules, imagePath, directories, createdAt, updatedAt, sessionIds
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        description = try container.decode(String.self, forKey: .description)
        rules = try container.decode(String.self, forKey: .rules)
        imagePath = try container.decodeIfPresent(String.self, forKey: .imagePath)
        directories = try container.decodeIfPresent([String].self, forKey: .directories) ?? []
        createdAt = try container.decode(Date.self, forKey: .createdAt)
        updatedAt = try container.decode(Date.self, forKey: .updatedAt)
        sessionIds = try container.decode([String].self, forKey: .sessionIds)
    }
}

/// Type of chat session.
enum SessionType: String, Codable, Sendable {
    case main
    case group
    case cron
    case subagent
    case channel
    case git
}

/// Parsed session key following canonical format.
struct SessionKey: Codable, Sendable, Hashable {
    let type: SessionType
    let identifier: String
    let timestamp: Date?

    /// Parse a session key string like "main", "group:abc", "cron:daily-report:2026-03-08"
    static func parse(_ raw: String) -> SessionKey {
        let parts = raw.split(separator: ":", maxSplits: 2).map(String.init)
        let type = SessionType(rawValue: parts.first ?? "main") ?? .main
        let identifier = parts.count > 1 ? parts[1] : "default"
        return SessionKey(type: type, identifier: identifier, timestamp: nil)
    }
}
