import Foundation

// MARK: - Agent Install Plan

/// A parsed installation plan generated by the AI from a user-pasted install prompt.
struct AgentInstallPlan: Identifiable, Codable, Sendable {
    let id: UUID
    let name: String
    let description: String
    let sourcePrompt: String
    let steps: [AgentInstallStep]
    let warnings: [String]
    let timestamp: Date

    init(
        id: UUID = UUID(),
        name: String,
        description: String,
        sourcePrompt: String,
        steps: [AgentInstallStep],
        warnings: [String] = [],
        timestamp: Date = Date()
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.sourcePrompt = sourcePrompt
        self.steps = steps
        self.warnings = warnings
        self.timestamp = timestamp
    }
}

/// A single step within an installation plan.
struct AgentInstallStep: Identifiable, Codable, Sendable {
    let id: UUID
    let order: Int
    let description: String
    let command: String
    let workingDirectory: String?
    var status: AgentInstallStepStatus
    var output: String?
    var exitCode: Int32?

    init(
        id: UUID = UUID(),
        order: Int,
        description: String,
        command: String,
        workingDirectory: String? = nil,
        status: AgentInstallStepStatus = .pending,
        output: String? = nil,
        exitCode: Int32? = nil
    ) {
        self.id = id
        self.order = order
        self.description = description
        self.command = command
        self.workingDirectory = workingDirectory
        self.status = status
        self.output = output
        self.exitCode = exitCode
    }
}

/// Status of an individual install step.
enum AgentInstallStepStatus: String, Codable, Sendable {
    case pending
    case awaitingApproval
    case running
    case completed
    case failed
    case skipped
    case denied
}

// MARK: - Install Record (persisted)

/// A completed installation record stored in the registry.
struct AgentInstallRecord: Identifiable, Codable, Sendable {
    let id: UUID
    let name: String
    let description: String
    let sourcePrompt: String
    let steps: [AgentInstallStep]
    let installedAt: Date
    let providerId: String

    init(
        id: UUID = UUID(),
        name: String,
        description: String,
        sourcePrompt: String,
        steps: [AgentInstallStep],
        installedAt: Date = Date(),
        providerId: String
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.sourcePrompt = sourcePrompt
        self.steps = steps
        self.installedAt = installedAt
        self.providerId = providerId
    }
}

// MARK: - Install Phase (UI state)

/// Current phase of the agent install flow.
enum AgentInstallPhase: Sendable {
    case idle
    case parsing
    case reviewingPlan(AgentInstallPlan)
    case executing(AgentInstallPlan)
    case completed(AgentInstallRecord)
    case failed(String)
}
